# Deep Learning/ Artificial Neural Networks

In [1]:

import numpy as np
import pandas as pd
import tensorflow as tf


C:\Users\turtl\anaconda3\envs\tf\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
dataset = pd.read_csv('card.csv',skiprows=[1],index_col=[0])
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


[[ 20000      2      2 ...      0      0      0]
 [120000      2      2 ...   1000      0   2000]
 [ 90000      2      2 ...   1000   1000   5000]
 ...
 [ 30000      1      2 ...   4200   2000   3100]
 [ 80000      1      3 ...   1926  52964   1804]
 [ 50000      1      2 ...   1000   1000   1000]]
[1 1 0 ... 1 1 1]


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0000e+00 1.0000e+00 2.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e+00 1.2000e+01 ... 1.0000e+03 0.0000e+00 2.0000e+03]
 [0.0000e+00 1.0000e+00 9.0000e+00 ... 1.0000e+03 1.0000e+03 5.0000e+03]
 ...
 [1.0000e+00 0.0000e+00 3.0000e+00 ... 4.2000e+03 2.0000e+03 3.1000e+03]
 [1.0000e+00 0.0000e+00 8.0000e+00 ... 1.9260e+03 5.2964e+04 1.8040e+03]
 [1.0000e+00 0.0000e+00 5.0000e+00 ... 1.0000e+03 1.0000e+03 1.0000e+03]]
[[0.0000e+00 1.0000e+00 0.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 1.0000e+03 0.0000e+00 2.0000e+03]
 [0.0000e+00 1.0000e+00 0.0000e+00 ... 1.0000e+03 1.0000e+03 5.0000e+03]
 ...
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 4.2000e+03 2.0000e+03 3.1000e+03]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 1.9260e+03 5.2964e+04 1.8040e+03]
 [1.0000e+00 0.0000e+00 1.0000e+00 ... 1.0000e+03 1.0000e+03 1.0000e+03]]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1234)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## 3 layers of ANN

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
704/704 [==============================] - 4s 3ms/step - loss: 0.5416 - accuracy: 0.7424
Epoch 2/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4541 - accuracy: 0.8148
Epoch 3/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4467 - accuracy: 0.8184
Epoch 4/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4433 - accuracy: 0.8184
Epoch 5/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4411 - accuracy: 0.8204
Epoch 6/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4393 - accuracy: 0.8200
Epoch 7/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4383 - accuracy: 0.8209
Epoch 8/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4375 - accuracy: 0.8204
Epoch 9/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4369 - accuracy: 0.8207
Epoch 10/100
704/704 [==============================] - 2s 3ms/step - loss: 0.4362 - accura

In [14]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

235/235 [==============================] - 1s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[5511  289]
 [1087  613]]


0.8165333333333333

81.653% accuracy